### ISSUE TITLE
truffle console error

### ISSUE THREAD

**Issue by Akanryan502** [didil/stone-dapp#5]
Please how can i fix this...
Error: Token has not been deployed to detected network (network/artifact mismatch)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.deployed (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:85:1)
    at Object.checkNetworkArtifactMatch (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/utils/index.js:271:1)
Any idea i appreciated... Thank You

**Comment by didil** [comment]
@Akanryan502  did you migrate the contract via `truffle migrate` first ?

**Comment by Akanryan502** [comment]
Yes boss... I even deployed the first smart contract I built... didn't throw this error...

**Comment by ghost** [comment]
Did you try npm uninstall -g truffle and then an npm install -g truffle ? If yes then can you please check your network configuration file ? @Akanryan502

**Comment by ghost** [comment]
I have same problem. How did you fix this? @Akanryan502

**Comment by ghost** [comment]
@Mazekeen08  your answer helped me thanks <3
